version: '2.18.1'

services: 

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'

    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest

    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    
  mysqldb:
      image: mysql:latest
      container_name: 'mydb'
      environment: 
      - MYSQL_ROOT_PASSWORD=123456
      volumes: 
        - ./db:/docker-entrypoint-initdb.d
        - mysqlVolume:/var/lib/mysql
        - mysqlConfig:/etc/mysql

     
  docker-consumidor:
      build:
          context: ./docker-consumidor/
      
  
  docker-produtor:
      build:
          context: ./docker-produtor/
      
        
  docker-ator:
      build:
          context: ./Ator/
      ports:
        - 8000:5000
      
  
volumes: 
    mysqlVolume:
    mysqlConfig: