version: '3.6'

services: 

  rabbitmq:
    image: rabbitmq:3-management

    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest

    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    

  mysqldb:
    image: mysql:latest
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
    volumes: 
      - ./db:/docker-entrypoint-initdb.d
      - mysqlVolume:/var/lib/mysql
      - mysqlConfig:/etc/mysql

  docker-consumidor:
    build:
      context: ./docker-consumidor/
      
    depends_on: 
      - rabbitmq
      - mysqldb
    
    links:
      - rabbitmq
      
  
  docker-produtor:
      build:
          context: ./docker-produtor/
      
      depends_on: 
          - rabbitmq
  
  docker-ator:
      build:
          context: ./Ator/
      
      ports:
        - 8000:5000
      
  
volumes: 
    mysqlVolume:
    mysqlConfig: